# Generated by Django 2.2.15 on 2020-09-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipe', '0002_auto_20200914_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipe',
        ),
    ]
